name: rake
description: A basic implementation of RAKE (Rapid Automatic Keyword Extraction.
version: 1.0.0
author: Mathis Gerdes <mathisgerdes@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
